import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Sidebar from './../components/Sidebar'
import styled from 'styled-components';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>E Messenger</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
    </div>
  )
}

export default Home
